# Learn more about Configuration as Code: https://docs.gatling.io/reference/execute/cloud/user/configuration-as-code
# This file is full deployment configuration file example.
# Please note all these configuration fields, or even this file, are optional.

gatling.enterprise.package {
  # Consistent deployment using an existing package ID
  # https://docs.gatling.io/reference/execute/cloud/user/configuration-as-code/#consistent-deployment-with-id
  id = "package_rgx1u66mxtddupo8q4ugthqk8h"
  name = "jules_github_actions"
  team = "Default" # or ID with team = "00000000-0000-0000-0000-000000000000"
  simulations = [
    {
      # Consistent deployment using an existing simulation ID
      # https://docs.gatling.io/reference/execute/cloud/user/configuration-as-code/#consistent-deployment-with-id
      id = "test_emko3raet7nh8qu8jyue3huiih"
      name = "jules_github_actions"
      # FQCN Fully Qualified Class Name
      simulation = "example.BasicSimulation"
    }
  ]
}

